### ISSUE TITLE
Tabs vs Spaces -- The blind remix.

### ISSUE THREAD

**Issue by dlikhten** [testdouble/standard#158]

**Comment by dlikhten** [comment]
Is it possible to add an option for tabs vs spaces. Some engineers with vision problems (different kinds) really find changing the tab-width of their editor helps significantly.

Curious if this is a strong enough problem to warrant a flag, or a fork.

**Comment by dgutov** [comment]
Sounds like a good cause for an editor plugin (to display indentation differently) rather than a reason to change how to file is saved on disk. Your team probably has different kinds of engineers.

**Comment by dlikhten** [comment]
Isn't that literally the purpose of tabs? Characters that can be displayed differently based on people's editor preferences?

**Comment by dgutov** [comment]
It differs. People and editors use tabs in a variety of ways.

E.g. the GNU project historically used a mixture of tabs and spaces to "save disk space". In that scheme you could have one tab character per several indentation levels.

**Comment by dlikhten** [comment]
Okay I will be very clear: I am in absolutely no way advocating for Tabs being used for saving bits. Nobody cares about that.

You're right historically tabs have been used differently.

My question was: Is accessibility a worthwhile reason to make it an option, or is it more appropriate to make a fork?

**Comment by schpet** [comment]
FWIW i'm able to use rubocop with standard's rules as described in #30, using tabs instead of spaces with the following `.rubocop.yml`:

```yaml
require:
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

Layout/IndentationStyle:
  Enabled: true
  EnforcedStyle: tabs
  IndentationWidth: 1

Layout/IndentationWidth:
  Width: 1
```

this means i run `bundle exec rubocop` and not `bundle exec standardrb`
