### ISSUE TITLE
Consider updating `Style/HashSyntax` to `ruby19` 

### ISSUE THREAD

**Issue by tejasbubane** [testdouble/standard#259]
### Current

```
$ standardrb --version
0.13.0
```

[base config](https://github.com/testdouble/standard/blob/9b5f084390b4f41a1b679ab58721283c8ec86f1d/config/base.yml#L892-L894):
```yml
Style/HashSyntax:
  Enabled: true
  EnforcedStyle: ruby19_no_mixed_keys
```

registers offense for:
```ruby
# when keys are strings
validates :email, 'spree/email' => true, allow_blank: true

# when keys are variables
address.update!(column_for_default => true, archived: false)
```

### Proposed change

`EnforcedStyle: ruby19` (rubocop's default). Does not register offense for above cases.
