### ISSUE TITLE
Feedback & proposals

### ISSUE THREAD

**Issue by palkan** [testdouble/standard#30]
Hey @searls)

Replying to https://twitter.com/searls/status/1066359371599360000.

_[offtopic]_ Btw, what about having a dedicated issue for feedback and proposals (e.g. this one)? 

I've added `standard` to the project I'm currently working on right after your LT at RubyConf (it was great, thank you).

I'm using it as a default RuboCop config (not as a standalone tool):

```yml
# .rubocop.yml
require:
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml
```

Why? For several reasons:

1) I have some third-party cops and RuboCop plugins, and, as I see, it's impossible to use them directly with `standard`.

I'm not sure that `standard` config should handle custom plugin integration–looks like an overkill to me. Using RuboCop with `standard` config (like we do) works fine.

Thus, I suggest **adding a documentation on how to use standard config with RuboCop for advanced usage**.

Btw, there was an idea to add _presets_ functionality to RuboCop (see https://github.com/rubocop-hq/rubocop/issues/5612); maybe, in the future, `standard` could be a RuboCop preset and not a wrapper.

2) **Trailing comma enforcement**

Ok, my config is a little bit more complicated:

```yml
inherit_from: "./rspec.yml"

require:
  - standard/cop/semantic_blocks

inherit_gem:
  standard: config/base.yml

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: no_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: no_comma
```

I know the reasoning behind the trailing comma, but I still cannot unlearn using this style. And I don't think this style is popular among Rubyists (I've never seen it in any project); for me it looks like something from JS world)

Maybe, the reason this style is not popular is that RuboCop by default enforces `no_comma`.

What about having a config param to control this behaviour (say `trailing_comma: yes | no`) or disable these cops at all?

3) Semantic blocks.

Another _holy-war-ish_ thing, IMO. And could block the adoption of `standard` ([one-liner vs. multi-liner](https://twitter.com/mikker/status/1066375976752422913) rule is much simpler).

TBH, I haven't heard about this style ever (being a RuboCop user and contributor for more than three years).

So, in my config I turned this cop off (_the fear of unknown_ 🙀).

Btw, there is [a proposal](https://github.com/rubocop-hq/rubocop/issues/6393) to add this style to RuboCop as a config option to `Style/BlockDelimiters`. Having this in RuboCop itself seems like a better idea than adding a custom cop along with the `standard`.

4) Default ignores.

Although `standard` allows to configure ignore paths, it would be great if it has some default values which could cover most use-cases–so you can run `standard` without adding a configuration at all.

My _default_ ignore list looks like this:

```yml
AllCops:
  Exclude:
    # auto-generated binstubs
    - 'bin/*'
    # temp files
    - 'tmp/**/*'
    # node_modules could contain Ruby code
    - 'node_modules/**/*'
    # vendor/ dir is used by most CI services
    - 'vendor/**/*'
```
