### ISSUE TITLE
Documentation Issue: Unclear How to Force Standardrb Rules to Take Precedence Over RuboCop Rules

### ISSUE THREAD

**Issue by todd-a-jacobs** [testdouble/standard#328]
I really like standard, because it provides a much more minimalist approach to linting and other issues that (IMHO) RuboCop goes overboard on. However, some shops use RuboCop in CI, rather than standard, and it's unclear how to ensure that standard's rules take precedence.

After reading RuboCop's [inheritance section](https://docs.rubocop.org/rubocop/configuration.html#inheriting-from-another-configuration-file-in-the-project) and reviewing the README for standard, it's unclear how to ensure that RuboCop uses standard's rules and todo rather than its own.

As an example, I tried this:

``` yaml
# .rubocop.yml

require:
  - rubocop-rake                                                                                                                                             
  - rubocop-rspec
  - standard

inherit_from: .rubocop_todo.yml
inherit_from: .standard_todo.yml
inhereit_gem:
  standard: config/base.yml
```

which didn't accomplish the task.  Is there a way to ensure that standard's rules and todo take precedence if run by RuboCop?
