### ISSUE TITLE
Standard rule precedence lost when running through rubocop.yml

### ISSUE THREAD

**Issue by fragkakis** [testdouble/standard#392]
Hello,

I was using the standard gem until now, but I wanted to try also out [rubocop-rails](https://github.com/rubocop/rubocop-rails) gem. I created the following `rubocop.yml`:

```yaml
require:
  - standard
  - rubocop-rails

inherit_gem:
  standard: config/base.yml
```

The problem I have is that now it seems that the `standard` somehow lost precedence, as I can see a lot of violations for `Style/StringLiterals` suggesting I should use single quotes (while the opposite was the case when only using the `standard` gem):

```
 Line #1 – convention: Style/StringLiterals: Prefer single-quoted strings when you don't need string interpolation or special symbols. 
```

Is there an error on my `rubocop.yml` file?
