### ISSUE TITLE
RuboCop unsupported Ruby version 2.5

### ISSUE THREAD

**Issue by klausmeyer** [testdouble/standard#413]
Hi,

I've just upgraded to v1.12.0 in an app where I use standard gem together with rubocop.

When executing `rubocop` I'm getting this error:

```
Error: RuboCop found unsupported Ruby version 2.5 in `TargetRubyVersion` parameter (in .rubocop.yml). 2.5-compatible analysis was dropped after version 1.28.

Supported versions: 2.6, 2.7, 3.0, 3.1, 3.2
```

Here my `.rubocop.yml`:

```yaml
require: standard

inherit_gem:
  standard: config/base.yml

AllCops:
  TargetRubyVersion: 3.1
  SuggestExtensions: false
  Exclude:
    - db/schema.rb
```

A quick workaround is to override the `TargetRubyVersion` defined by standard but maybe it could be fixed in the gem itself by dropping support for Ruby 2.5 as well.

```diff
diff --git .rubocop.yml .rubocop.yml
--- .rubocop.yml
+++ .rubocop.yml
@@ -4,6 +4,7 @@ inherit_gem:
   standard: config/base.yml

 AllCops:
+  TargetRubyVersion: 3.1
   SuggestExtensions: false
   Exclude:
     - db/schema.rb
```

Should I provide a PR for this? I assume it's mainly changing this line to 2.6:

https://github.com/testdouble/standard/blob/6fe68aa19bc6bb6be8adceaf6e443f79f0429b6c/config/base.yml#L6
