### ISSUE TITLE
extend_config vs .rubocop_todo.yml

### ISSUE THREAD

**Issue by palkan** [testdouble/standard#540]
**Standard**: 1.24.3
**RuboCop:** 1.44.1

I've been working on the [blog post](https://evilmartians.com/chronicles/rubocoping-with-legacy-bring-your-ruby-code-up-to-standard) update, and found that it's not possible to migrate the project from `.rubocop_todo.yml` to `standardrb` without re-generating the TODO file with `standard`.

## Reproduction script

Given the source code file (`a.rb`):

```ruby
module A
  def foo; 'bar'; end
end
```

And the following configuration files:

```yml
# .rubocop.yml
inherit_mode:
  merge:
    - Exclude

require:
  - standard

inherit_gem:
  standard: config/base.yml

inherit_from:
  - .rubocop_todo.yml

AllCops:
  NewCops: disable
  SuggestExtensions: false
  TargetRubyVersion: 2.6
```

```yml
# .standard.yml
parallel: true
format: progress

extend_config:
  - .rubocop_todo.yml
```

The TODO file has been generated with RuboCop and contains:

```yml
Style/SingleLineMethods:
  Exclude:
    - 'a.rb'

Style/StringLiterals:
  EnforcedStyle: single_quotes
``` 

## Adding `.rubocop_todo.yml`  has no effect

I expect running `standardrb` to show no errors, but:

```sh
$ be standardrb

Inspecting 1 file
C

Offenses:

a.rb:2:3: C: [Correctable] Style/SingleLineMethods: Avoid single-line method definitions.
  def foo; 'bar'; end
  ^^^^^^^^^^^^^^^^^^^
a.rb:2:12: C: [Correctable] Style/StringLiterals: Prefer double-quoted strings unless you need single quotes to avoid extra backslashes for escaping.
  def foo; 'bar'; end
           ^^^^^
```

Running `rubocop` works as expected: `1 file, no offenses detected`.

## Possible solutions

I think, it's okay to instruct users to run `standardrb --generate-todo` instead of loading the existing `.rubocop_todo.yml`. Thus, just a note in the documentation could be enough.

However, it's not clear why extending the configuration doesn't work in this case. Maybe, something related to the `inherit_mode`?
